name: Run Postman Tests with Newman

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman
      
      - name: Install Newman HTML reporter
        run: npm install -g newman-reporter-html  

      - name: Run Postman tests with Newman
        run: |
          newman run collection2.json \
            -e enviroment.json \
            --reporters cli,junit \
            --reporter-html-export results/report.html

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: postman-report
          path: results/report.xml

    
